version: '3.4'
services:
  db:
    container_name: devops_db
    image: postgres:11.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  cache:
    container_name: devops_cache
    image: redis:5.0
    restart: always
    ports:
      - 6379:6379
  broker:
    container_name: devops_broker
    image: rabbitmq:3.7
    restart: always
    ports:
      - 5672:5672
